{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "soundops.fullname" . }}-limits
  labels:
    {{- include "soundops.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 250m
        memory: 512Mi
      default:
        cpu: "1"
        memory: 2Gi
{{- end }}
